import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The terms governing use of Synaptiq\'s A-Level Maths AI tutoring platform.',
  robots: { index: true, follow: true },
  openGraph: {
    title: 'Terms & Conditions — Synaptiq',
    description: 'The terms governing use of Synaptiq\'s A-Level Maths AI tutoring platform.',
    type: 'website',
  },
}

export default function TermsPage() {
  return (
    <div style={{ background: '#08090E', color: '#E8F0FF', minHeight: '100vh', fontFamily: '\'DM Sans\', system-ui, sans-serif', lineHeight: 1.7 }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '3rem 1.5rem 5rem' }}>
        <Link href="/" style={{ display: 'inline-block', fontWeight: 800, fontSize: '1.3rem', color: '#C9A84C', textDecoration: 'none', marginBottom: '2.5rem' }}>
          Synaptiq
        </Link>
        <h1 style={{ fontFamily: '\'Syne\', sans-serif', fontSize: '2rem', fontWeight: 800, marginBottom: '0.4rem' }}>Terms &amp; Conditions</h1>
        <p style={{ color: '#6B7394', fontSize: '0.85rem', marginBottom: '2rem' }}>Last updated: 1 March 2026 · Synaptiq Ltd</p>

        <div style={{ background: 'rgba(201,168,76,0.08)', border: '1px solid rgba(201,168,76,0.2)', borderRadius: 12, padding: '1.25rem 1.5rem', marginBottom: '2rem' }}>
          <strong>Plain English:</strong> Use Synaptiq for learning. Don&apos;t abuse the platform or try to cheat. Pay your subscription. You own your content. We own the platform. We&apos;re not responsible if the AI gets something wrong — always verify important answers.
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By creating an account or using Synaptiq, you agree to these Terms and Conditions and our Privacy Policy. If you do not agree, do not use the platform. If you are under 18, a parent or guardian must agree on your behalf.</p>
        </Section>

        <Section title="2. The Service">
          <p>Synaptiq provides an AI-powered educational platform including but not limited to: AI tutoring, practice question generation, essay marking, revision tools, and progress tracking. We reserve the right to modify, suspend, or discontinue any feature at any time with reasonable notice.</p>
        </Section>

        <Section title="3. Account Registration">
          <ul>
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for keeping your password secure</li>
            <li>You must be 13 or older to create an account. Users under 13 require parental consent</li>
            <li>One account per person — sharing accounts is not permitted</li>
            <li>We reserve the right to suspend or terminate accounts that violate these terms</li>
          </ul>
        </Section>

        <Section title="4. Subscriptions and Payment">
          <ul>
            <li>Subscriptions are billed monthly in advance</li>
            <li>Prices are in GBP and inclusive of VAT where applicable</li>
            <li>You may cancel your subscription at any time — cancellation takes effect at the end of the current billing period</li>
            <li>We do not offer refunds for partial months except where required by UK consumer law</li>
            <li>We reserve the right to change prices with 30 days notice</li>
            <li>Payment is processed by Stripe — we do not store card details</li>
          </ul>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to use Synaptiq to:</p>
          <ul>
            <li>Submit work generated by the AI as your own in academic assessments without disclosure (academic dishonesty)</li>
            <li>Upload or share illegal, harmful, or offensive content</li>
            <li>Attempt to reverse engineer, scrape, or copy the platform</li>
            <li>Share your login credentials with others</li>
            <li>Use the platform in any way that violates applicable law</li>
            <li>Harass, abuse, or harm other users</li>
          </ul>
        </Section>

        <Section title="6. AI-Generated Content">
          <div style={{ background: 'rgba(251,113,133,0.08)', border: '1px solid rgba(251,113,133,0.2)', borderRadius: 12, padding: '1.25rem 1.5rem' }}>
            <strong>Important:</strong> Synaptiq uses artificial intelligence to generate educational content. While we work hard to ensure accuracy:
            <ul style={{ marginTop: '0.5rem' }}>
              <li>AI responses may occasionally contain errors or inaccuracies</li>
              <li>AI content should not replace professional advice (medical, legal, financial)</li>
              <li>For high-stakes decisions, always verify information with authoritative sources</li>
              <li>Exam preparation content is guidance only — always check your official specification</li>
            </ul>
          </div>
        </Section>

        <Section title="7. Intellectual Property">
          <ul>
            <li>Synaptiq owns all platform code, design, branding, and proprietary content</li>
            <li>You retain ownership of content you create (your notes, essays, flashcards)</li>
            <li>You grant us a limited licence to process your content to provide the service</li>
            <li>AI-generated responses are provided to you for personal educational use only</li>
          </ul>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>To the maximum extent permitted by UK law, Synaptiq shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability to you shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          <p>Nothing in these terms excludes liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded by law.</p>
        </Section>

        <Section title="9. Consumer Rights">
          <p>If you are a consumer in the UK, you have statutory rights that these terms do not affect. Under the Consumer Rights Act 2015, digital services must be of satisfactory quality and fit for purpose. If our service does not meet this standard, you may be entitled to a remedy.</p>
        </Section>

        <Section title="10. Termination">
          <p>You may delete your account at any time via Settings. We may terminate your account if you breach these terms, with or without notice depending on severity. On termination, your access ends immediately and your data will be deleted in accordance with our Privacy Policy.</p>
        </Section>

        <Section title="11. Governing Law">
          <p>These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales, except where consumer protection law provides otherwise.</p>
        </Section>

        <Section title="12. Changes to Terms">
          <p>We may update these terms from time to time. We will give you at least 30 days notice of material changes by email. Continued use after that period constitutes acceptance.</p>
        </Section>

        <div style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid rgba(255,255,255,0.07)', display: 'flex', gap: '1.5rem', fontSize: '0.875rem' }}>
          <Link href="/" style={{ color: '#C9A84C', textDecoration: 'none' }}>← Back</Link>
          <Link href="/privacy" style={{ color: '#6B7394', textDecoration: 'none' }}>Privacy Policy</Link>
          <Link href="/cookies" style={{ color: '#6B7394', textDecoration: 'none' }}>Cookie Policy</Link>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '2rem' }}>
      <h2 style={{ fontFamily: '\'Syne\', sans-serif', fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.75rem', color: '#E8F0FF' }}>{title}</h2>
      <div style={{ color: '#A8B8CC' }}>
        {children}
      </div>
    </div>
  )
}
